/**
 * Syncs Supabase URL and anon key from repo root .env to frontend/.env
 * so developers only maintain the root .env. Run from repo root:
 *   node scripts/sync-env.js
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const frontendEnvPath = path.join(rootDir, 'frontend', '.env');

function parseEnv(content) {
  const out = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

if (!fs.existsSync(envPath)) {
  console.error('Root .env not found. Copy .env.example to .env and set SUPABASE_URL and SUPABASE_ANON_KEY.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
const url = env.SUPABASE_URL || '';
const anonKey = env.SUPABASE_ANON_KEY || '';

if (!url || !anonKey) {
  console.error('SUPABASE_URL and SUPABASE_ANON_KEY must be set in root .env');
  process.exit(1);
}

const lines = [
  '# Auto-generated by scripts/sync-env.js – do not commit if it contains secrets',
  '# Source: repo root .env',
  '',
  'VITE_SUPABASE_URL=' + url,
  'VITE_SUPABASE_ANON_KEY=' + anonKey,
  '',
  '# Backend API base URL (optional; default in code: http://localhost:4000)',
  '# VITE_API_URL=http://localhost:4000',
  '',
];

fs.writeFileSync(frontendEnvPath, lines.join('\n'), 'utf8');
console.log('Wrote frontend/.env with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY from root .env');
