-- Enable pgvector for future semantic search (safe to run on Supabase — pre-installed)
CREATE EXTENSION IF NOT EXISTS vector;

-- Add AI-generated summary columns to channels and workspaces.
-- These are periodically regenerated by the background worker after new messages arrive.
ALTER TABLE public.channels
    ADD COLUMN IF NOT EXISTS summary text,
    ADD COLUMN IF NOT EXISTS summary_updated_at timestamptz;

ALTER TABLE public.workspaces
    ADD COLUMN IF NOT EXISTS summary text,
    ADD COLUMN IF NOT EXISTS summary_updated_at timestamptz;
